#!/bin/bash

var=1

function trap_ctrlc () {
    echo [1m[31mCaught ctrlc $var[0m
    test $var -ge 10 && exit 124
    var=$(expr $var + 1)
}

trap 'trap_ctrlc' 2

if [[ "$1" == "run" ]]; then
  cmd="make run"
elif [[ "$1" == "comp" ]]; then
  cmd="make comp"
else
  cmd="make test"
fi

# Ref: https://stackoverflow.com/questions/12771909/bash-using-trap-ctrlc
while [ 1 ]; do
    clear && tmux clear-history
    $cmd
    echo -en Press Enter to continue
    read newline
done
