#!/bin/bash
# Usage: algo-run elf res_name
set -o pipefail

function trap_ctrlc () {
    echo [1m[31mLoop exists, see log file. Exit...[0m
    exit 2
}

# Initialise trap to call trap_ctrlc function
# when signal 2 (SIGINT) is received
trap "trap_ctrlc" 2

inp=*.in
elf=${1:-elf}
res=${2:-test.res}

rm $res
for i in $inp; do
    if ! [ -e "$i" ]; then
        echo [1m[31mEmpty input[0m
        exit 1
    fi
    echo "//-------------------------------------------------------------\\\\"
    out="${i%.in}".out
    # Ref: https://unix.stackexchange.com/questions/53289/does-segmentation-fault-message-come-under-stderr
    if ! { ./$elf < $i; } | tee $out; then
      echo [1m[31mRuntime error, Check source code, Please :\(\-[0m
    else
      cat $out >> $res
    fi
    echo "\\\\-------------------------------------------------------------//"
    rm -f $i $out
done
