#!/usr/bin/env bash

var=1
trap '{ echo $var && test $var -eq 10 && exit 1; var=$(expr $var + 1); }' INT

makefile=$1
run=$2

if [[ "$1" == "test" ]]; then
  cmd="make test -f $2"
elif [[ "$1" == "run" ]]; then
  cmd="make run -f $2"
else
  cmd="make test"
fi

while 1; clear && tmux clear-history; do $cmd; \
echo -n "Press Enter to continue"; read newline; \
clear && tmux clear-history; done;
