#!/usr/bin/env python3

import os
import sys
import copy
from pathlib import Path

print('Run multiple algorithm samples\n')

sample = ""
samples = [];
sep = ""
with open(sys.argv[1], 'r') as f:
  for line in f:
    if line != '\n':
      sample += line
    else:
      if sample != '':
        samples.append(copy.deepcopy(sample))
        sample = ""

if sample != '':
  samples.append(copy.deepcopy(sample))
  # print(samples)

ret = []
for i, sample_content in enumerate(samples):
  input_name = 'input_' + str(i) + '.txt'
  output_name = 'output_' + str(i) + '.txt'
  with open(input_name, 'w') as f:
    f.write(sample_content)
  cwd = str(Path.cwd())
  cmd = cwd + '/elf < ' + input_name + '> ' + output_name
  os.system(cmd)
  with open (output_name, 'r') as f:
    for line in f:
      ret.append(line)
      print(line, end='')
  print("========================")
  os.system('rm ' + input_name)
  os.system('rm ' + output_name)

# print(ret)
with open('result.txt', 'w') as f:
  for line in ret:
    f.write(line)
