#!/usr/bin/env bash
root=${ALGO:=$HOME/Code/algos}
for filepath in $*; do
    mkdir -p $filepath
    filename=$(basename "$filepath")
    ctime=$(date)
    sed -e "s/\\\$NAME/$filename/g" \
        -e "s/\\\$DATE/$ctime/g" \
        "$root/template.cpp" > $filepath/$filename.cpp
    cp "$root/Makefile" $filepath/Makefile
    touch $filepath/ins
    echo "==> Problem $filepath created."
    subl $filepath/true
    subl $filepath/*
    cd $filepath
    while [ 1 ]; do
        clear && tmux clear-history
        make
        echo -en "\nPress Enter to continue"
        read newline
        clear && tmux clear-history
    done
done
